<a href="https://colab.research.google.com/github/HarishVaradharajan/tensorflow/blob/main/add_diff_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
x=tf.constant(5)
y=tf.constant(6)
z=tf.multiply(x,y)
add=tf.add(x,y)
print(z)
print(add)

tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)


In [ ]:
import numpy as np
x = np.array(5)
y = np.array(6)
add = x + y
print(add)

11


In [ ]:
x=tf.constant([1, 2, 3])
y=tf.constant([4, 5, 6])
z=tf.multiply(x,y)
add=tf.add(x,y)
print(z)
print(add)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
import numpy as np
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
vector_sum = np.add(vector_a, vector_b)
print(vector_sum)

[5 7 9]


In [ ]:
a = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)
b= tf.constant([[5, 6], [7, 8]], dtype=tf.int32)
add=tf.add(x,y)
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_sum = np.add(matrix_a, matrix_b)
print(matrix_sum)

[[ 6  8]
 [10 12]]
